**Limpieza de Datos**

Para emepezar tenemos que cargar y limpiar la base de datos usando al libreria de Pandas.

In [118]:
import pandas as pd
import numpy as np

In [119]:
df = pd.read_csv("../data/ensanut2022_muestras.csv", sep=";")
df.head()

,FOLIO_I,FOLIO_INT,t_hora,t_min,t_sumai,t_sumaf,hora_ini_1,fecha_ini_1,hora_fin_1,fecha_fin_1,...,valor_VIT_D,fecdeterm_VIT_D,ponde_v,cuenta_mic,ponde_m12a49,ponde_m0a11,estrato,region,est_sel,upm
0,2022_01001004,2022_01001004_01,13,35,813,815,13:33:14,10/11/2022,13:35:20,10/11/2022,...,,,,0,,,3,4,13,0100100011320
1,2022_01001008,2022_01001008_01,20,44,1244,1244,20:34:12,20/11/2022,20:34:55,20/11/2022,...,,,,0,,,3,4,13,0100100011320
2,2022_01001008,2022_01001008_03,20,43,1243,1243,20:41:51,20/11/2022,20:42:23,20/11/2022,...,,,,0,,,3,4,13,0100100011320
3,2022_01001009,2022_01001009_02,9,26,561,566,09:21:48,10/11/2022,09:26:03,10/11/2022,...,,,"16452,5523392573",0,,,3,4,13,0100100011320
4,2022_01001011,2022_01001011_01,20,49,1249,1249,20:45:31,20/11/2022,20:46:06,20/11/2022,...,,,,0,,,3,4,13,0100100011320

Empezamos por imprimir todas las columnas para luego escoger con cuales nos queremos quedar

In [120]:
for col in df.columns:
    print(col)

FOLIO_I
FOLIO_INT
t_hora
t_min
t_sumai
t_sumaf
hora_ini_1
fecha_ini_1
hora_fin_1
fecha_fin_1
tiempo1
resultado_1
hora_ini_2
fecha_ini_2
hora_fin_2
fecha_fin_2
tiempo2
resultado_2
hora_ini_3
fecha_ini_3
hora_fin_3
fecha_fin_3
tiempo3
resultado_3
hora_ini_4
fecha_ini_4
hora_fin_4
fecha_fin_4
tiempo4
resultado_4
hora_ini
fecha_ini
localizado
entidad
desc_ent
municipio
desc_mun
h0302
h0303
fech_nac
sc
sv
sh
sm
int_hemoglobina
nota1
nota11
nota00
sc01
sc02
sc03
sc04
nota01
san01
san02
san03
san04
san05
san06
nota02
hb01
hb02
hb03
hb04
hb05
hb06a
hb06b
hb07a
hb07b
hb08
hb09
hb10
hb11
nota03
mc01
mc02
mc03
comentario
tiempo
hora_fin
fecha_fin
completa
otroent
MATRIZ_SUERO
valor_AC_URICO
fecdeterm_AC_URICO
valor_ALBU
fecdeterm_ALBU
valor_COL_HDL
fecdeterm_COL_HDL
valor_COL_LDL
fecdeterm_COL_LDL
valor_COLEST
fecdeterm_COLEST
valor_CREAT
fecdeterm_CREAT
valor_GLU_SUERO
fecdeterm_GLU_SUERO
valor_INSULINA
fecdeterm_INSULINA
valor_PCR
fecdeterm_PCR
valor_TRIG
fecdeterm_TRIG
MATRIZ_SANGRE
valor_EAG
fecdeterm_EAG
valor_HB1AC
fecdeterm_HB1AC
MATRIZ_SUEROMICRO
valor_FERRITINA
fecdeterm_FERRITINA
valor_FOL
fecdeterm_FOL
valor_HCST
fecdeterm_HCST
valor_PROTCREAC
fecdeterm_PROTCREAC
valor_STFR_FEB23
fecdeterm_STFR_FEB23
valor_VIT_B12
fecdeterm_VIT_B12
valor_VIT_D
fecdeterm_VIT_D
ponde_v
cuenta_mic
ponde_m12a49
ponde_m0a11
estrato
region
est_sel
upm

In [121]:
wanted_columns = ["FOLIO_I", "entidad", "desc_ent", "municipio", 
                  "desc_mun", "h0302", "h0303", "valor_COL_HDL", 
                  "valor_COL_LDL", "valor_COLEST", "valor_GLU_SUERO", 
                  "valor_TRIG", "valor_EAG"]

numeric_cols = ["valor_COL_HDL", "valor_COL_LDL", "valor_COLEST", 
                  "valor_GLU_SUERO", "valor_TRIG", "valor_EAG"]
data = df[wanted_columns]

Ahora quitamos todas las filas que no tienen valores y cambiamos de tipo de datos

In [122]:
data[numeric_cols] = data[numeric_cols].replace({' ': pd.NA, ' ': pd.NA, ',': '.'})

C:\Users\juamp\AppData\Local\Temp\ipykernel_44108\3659208383.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data[numeric_cols] = data[numeric_cols].replace({' ': pd.NA, ' ': pd.NA, ',': '.'})

In [123]:
data = data.dropna()

In [124]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2054 entries, 3 to 13897
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FOLIO_I          2054 non-null   object
 1   entidad          2054 non-null   int64
 2   desc_ent         2054 non-null   object
 3   municipio        2054 non-null   int64
 4   desc_mun         2054 non-null   object
 5   h0302            2054 non-null   int64
 6   h0303            2054 non-null   int64
 7   valor_COL_HDL    2054 non-null   object
 8   valor_COL_LDL    2054 non-null   object
 9   valor_COLEST     2054 non-null   object
 10  valor_GLU_SUERO  2054 non-null   object
 11  valor_TRIG       2054 non-null   object
 12  valor_EAG        2054 non-null   object
dtypes: int64(4), object(9)
memory usage: 224.7+ KB

In [125]:
for col in numeric_cols:
    data[col] = data[col].str.replace(',', '.')

In [126]:
data[numeric_cols] = data[numeric_cols].astype('float')

In [127]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2054 entries, 3 to 13897
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   FOLIO_I          2054 non-null   object
 1   entidad          2054 non-null   int64
 2   desc_ent         2054 non-null   object
 3   municipio        2054 non-null   int64
 4   desc_mun         2054 non-null   object
 5   h0302            2054 non-null   int64
 6   h0303            2054 non-null   int64
 7   valor_COL_HDL    2054 non-null   float64
 8   valor_COL_LDL    2054 non-null   float64
 9   valor_COLEST     2054 non-null   float64
 10  valor_GLU_SUERO  2054 non-null   float64
 11  valor_TRIG       2054 non-null   float64
 12  valor_EAG        2054 non-null   float64
dtypes: float64(6), int64(4), object(3)
memory usage: 224.7+ KB

In [129]:
data.describe()

,entidad,municipio,h0302,h0303,valor_COL_HDL,valor_COL_LDL,valor_COLEST,valor_GLU_SUERO,valor_TRIG,valor_EAG
count,2054.000000,2054.000000,2054.000000,2054.000000,2054.000000,2054.000000,2054.000000,2054.000000,2054.000000,2054.000000
mean,16.053067,35.417235,1.622201,47.301850,40.869036,90.703797,154.037001,104.309348,163.860273,123.591042
std,8.523805,53.478155,0.484955,16.428665,15.102858,30.897603,48.097781,70.597848,127.813820,53.909932
min,1.000000,1.000000,1.000000,20.000000,9.000000,11.100000,24.000000,10.400000,23.000000,62.000000
25%,10.000000,8.000000,1.000000,34.000000,33.000000,69.000000,122.000000,81.000000,91.250000,100.000000
50%,15.000000,20.000000,2.000000,47.000000,40.000000,89.000000,151.000000,90.000000,131.000000,108.000000
75%,23.000000,39.000000,2.000000,60.000000,47.000000,109.000000,182.000000,102.000000,192.000000,123.000000
max,32.000000,515.000000,2.000000,96.000000,333.000000,303.000000,681.000000,2372.000000,1361.000000,1114.000000

Vamos a renombrar algunas de las columnas para poder entenderlo de manera mas facil

In [132]:
data = data.rename(columns={'h0302': 'sexo', 'h0303': 'edad'})

In [134]:
data

,FOLIO_I,entidad,desc_ent,municipio,desc_mun,sexo,edad,valor_COL_HDL,valor_COL_LDL,valor_COLEST,valor_GLU_SUERO,valor_TRIG,valor_EAG
3,2022_01001009,1,01 AGUASCALIENTES,1,001 AGUASCALIENTES,2,65,73.0,130.0,252.0,111.0,131.0,131.0
8,2022_01001013,1,01 AGUASCALIENTES,1,001 AGUASCALIENTES,1,35,49.0,107.0,203.0,106.0,297.0,105.0
13,2022_01001015,1,01 AGUASCALIENTES,1,001 AGUASCALIENTES,2,65,41.0,76.0,145.0,109.0,136.0,154.0
17,2022_01001024,1,01 AGUASCALIENTES,1,001 AGUASCALIENTES,2,30,42.0,84.0,139.0,98.0,121.0,123.0
19,2022_01001027,1,01 AGUASCALIENTES,1,001 AGUASCALIENTES,1,76,41.0,119.0,215.0,253.0,257.0,217.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13877,2022_32053032,32,32 ZACATECAS,53,053 VILLA GONZÁLEZ ORTEGA,2,47,25.0,90.0,150.0,240.0,241.0,260.0
13883,2022_32056004,32,32 ZACATECAS,56,056 ZACATECAS,2,40,27.0,44.0,76.0,56.0,71.0,105.0
13893,2022_32056026,32,32 ZACATECAS,56,056 ZACATECAS,2,69,21.0,44.0,74.0,70.0,230.0,105.0
13896,2022_32056029,32,32 ZACATECAS,56,056 ZACATECAS,1,67,44.0,96.0,171.0,89.0,207.0,105.0
13897,2022_32056029,32,32 ZACATECAS,56,056 ZACATECAS,2,31,31.0,46.0,90.0,58.0,69.0,100.0

In [141]:
data = data.reset_index().drop(columns=['index'])

Finalmente guardamos los datos limpios para poder trabajar con ellos de manera mas facil

In [144]:
data.to_csv('../data/clean_data.csv')